name: Build on request or merge

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pipenv'
      - run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install
      - name: Build
        run: pipenv run python converter.py
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: converted-lapwing-base.json
